name: Build, test and deploy to Azure Function App

on:
  push:
    branches:
    - main
    paths:
    - 'functions/**'
    - 'tests/**'
    - '.github/workflows/functionAppPipeline.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'functions'
  PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v3

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Resolve Project Dependencies Using Pip
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

  deploy-test-env:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v3
    
    - name: Deploy Azure Functions in test environment
      uses: Azure/functions-action@v1
      id: deploy-test-env
      with:
        app-name: ${{ secrets.AZURE_TEST_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_TEST_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true

  test-functions:
    runs-on: ubuntu-latest
    needs: deploy-test-env
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v3

    - name: Run tests of wrong requests
      run: python tests/test-parameters-input.py

    - name: Run tests of successful requests 
      run: python tests/test-website-lifecycle.py