# This workflow will build a Python app and deploy it to an Azure Functions App on Linux when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure Functions app.
# For instructions see https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python?pivots=python-mode-configuration
#
# To configure this workflow:
# 1. Set up the following secrets in your repository:
#   - AZURE_FUNCTIONAPP_PUBLISH_PROFILE
# 2. Change env variables for your configuration.
#
# For more information on:
#   - GitHub Actions for Azure: https://github.com/Azure/Actions
#   - Azure Functions Action: https://github.com/Azure/functions-action
#   - Publish Profile: https://github.com/Azure/functions-action#using-publish-profile-as-deployment-credential-recommended
#   - Azure Service Principal for RBAC: https://github.com/Azure/functions-action#using-azure-service-principal-for-rbac-as-deployment-credential
#
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples/tree/master/FunctionApp

name: Build, test and deploy to Azure Function App

on:
  push:
    branches:
    - main
    paths:
    - 'check-name/**'
    - 'copy-files/**'
    - 'create-account-storage/**'
    - 'create-container/**'
    - 'delete-account-storage/**'
    - 'delete-container/**'
    - 'disable-static-website/**'
    - 'enable-static-website/**'
    - '.github/workflows/functionAppPipeline.yml'
  workflow_dispatch:

env:
  AZURE_TEST_FUNCTIONAPP_NAME: 'test-functions-srs'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v3

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Resolve Project Dependencies Using Pip
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

  deploy-test-env:
    runs-on: ubuntu-latest
    environment: test
    steps:     
    - name: Deploy Azure Functions in test environment
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_TEST_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_TEST_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true

  test-functions:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Run unit tests
      run: python -m pytest --import-mode=append tests/